sonar.projectKey=fastapi-project
sonar.projectName=FastAPI Project
sonar.projectVersion=1.0

sonar.sources=.

#  VERY IMPORTANT
sonar.inclusions=**/*.py,**/*.html

# Python config
sonar.python.version=3

sonar.sourceEncoding=UTF-8
